### ISSUE TITLE
Issue in contact page

### ISSUE THREAD

**Issue by swajeet732** [drdrakeramoray123/ecoomerve#1]
In your project it doesn't render to contact page  . It's throw Error while visiting contact page.
Following is the solution to solve the above problem . 
Step 1: Create Contact.html file in shop\template file.
Step 2: Add the following code in contact.html file

{% extends 'shop/basic.html' %}
{% block title %} Contact Us {% endblock %}
{% block body %}
 <div class="container">
     <h3>Contact Us</h3>
     <form action="/shop/contact/" method="post">{% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Your Name">
  </div>
          <div class="form-group">
    <label for="name">Email</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter Your Email">
  </div>
          <div class="form-group">
    <label for="name">Phone</label>
    <input type="tel" class="form-control" id="phone" name="phone" placeholder="Enter Your Phone Number">
  </div>
          <div class="form-group">
   <div class="form-group">
    <label for="desc">How May We Help You ?</label>
    <textarea class="form-control" id="desc" name="desc" rows="3"></textarea>
       <button type="submit" class="btn btn-success">Submit</button>
  </div>

 {% endblock %}

**Comment by drdrakeramoray123** [comment]
Thanks for the advice and solution 
I'll working on and solve the above issue asap.

**Comment by drdrakeramoray123** [comment]
Contact page  Issue solved .
